version: '3.8'

services:

  # Redis
  redis:
    image: redis:7.0.6-alpine
    container_name: redis  
    expose:
      - 6379
  #Django application

  backend:
    image: backend
    restart: unless-stopped
    build: 
      context: .
    volumes:
      - .:/django_backend
    ports:
      - 8000:8000
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000


  # Celery
  celery:
    restart: always
    build: 
      context: .
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    command: celery -A backend worker --beat --scheduler django --loglevel=info
    volumes:
      - .:/django_backend
    container_name: celery
    depends_on:
      - redis
      - backend